Repository sigmf/SigMF, pull requests merged in 2021-09, with the labels that each got.

#105 Modifications to `extensions` per #103.
  extensions/adsb.sigmf-ext.md
  extensions/antenna.sigmf-ext.md
  extensions/capture_details.sigmf-ext.md
  extensions/rfml.sigmf-ext.md
  extensions/signal.sigmf-ext.md
  extensions/wifi.sigmf-ext.md
  sigmf-spec.md
Labels: bug-fix

#157 SigMF Collections
  extensions/antenna.sigmf-ext.md
  extensions/volatile.sigmf-ext.md
  sigmf-spec.md
Labels: enhancement, Pending Review

#158 Fixing extension string to remove 'v' character
  sigmf-spec.md
Labels: bug-fix

#159 Fix citation licensing
  CITATION.cff
  LICENSE.md
  sigmf-spec.md
Labels: bug-fix

#161 rc tag prep: spec clean-up
  sigmf-spec.md
Labels: enhancement

#177 fixing indentation and missing commas in schema
  sigmf/schema.json
Labels: bug-fix

#179 allow annotations greater than _or equal_ to 1
  sigmf/sigmffile.py
Labels: suggestion

#180 Fix errors creating SigMFFile objects that do not have datatype set
  sigmf/sigmffile.py
Labels: bug-fix
