Repository sigmf/SigMF, pull requests merged in 2021-11, with the labels that each got.

#191 explicit guidance on GeoJSON Foreign Members
  sigmf-spec.md
Labels: clarification

#185 added utility function to automate data type str generation
  README.md
  sigmf/utils.py
Labels: enhancement, code

#190 Draft of approach for non-conforming dataset support
  sigmf-spec.md
Labels: enhancement

#192 update RFC 2119 keyword usage
  sigmf-spec.md
Labels: suggestion, clarification
