Repository sigmf/SigMF, pull requests merged in 2022-12, with the labels that each got.

#250 CI Pipeline for Python Package
  .github/workflows/main.yml
Labels: suggestion, code

#249 Added Matrix chat info and monthly call to README
  README.md
Labels: meta

#257 application compliance language clarification
  sigmf-spec.md
Labels: clarification

#255 fix table of contents errors
  sigmf-spec.md
Labels: suggestion

#223 Untarless
  README.md
  sigmf/__init__.py
  sigmf/archivereader.py
  sigmf/error.py
  sigmf/sigmf_hash.py
  sigmf/sigmffile.py
  tests/test_archivereader.py
Labels: enhancement

#217 Added VALID_TOP_LEVEL_KEYS list
  sigmf/sigmffile.py
Labels: suggestion
